/*$file${.::blinky.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: blinky_console.qm
* File:  ${.::blinky.c}
*
* This code has been generated by QM 5.2.5 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${.::blinky.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"    /* QP/C framework API */
#include "bsp.h"    /* Board Support Package interface */

/* ask QM to declare the Blinky class --------------------------------------*/
/*$declare${AOs::Blinky} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Blinky} ...........................................................*/
typedef struct {
/* protected: */
    QActive super;

/* private: */
    QTimeEvt timeEvt;
} Blinky;

/* protected: */
static QState Blinky_initial(Blinky * const me, void const * const par);
static QState Blinky_SHORT PRESS STATE(Blinky * const me, QEvt const * const e);
static QState Blinky_Led OFF(Blinky * const me, QEvt const * const e);
static QState Blinky_Led ON(Blinky * const me, QEvt const * const e);
static QState Blinky_LONG PRESS STATE(Blinky * const me, QEvt const * const e);
static QState Blinky_Led ON(Blinky * const me, QEvt const * const e);
static QState Blinky_Led OFF(Blinky * const me, QEvt const * const e);
/*$enddecl${AOs::Blinky} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/* instantiate the Blinky active object ------------------------------------*/
static Blinky l_blinky;
QActive * const AO_Blinky = &l_blinky.super;

/* ask QM to define the Blinky class ---------------------------------------*/
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 700U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.0.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::Blinky_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Blinky_ctor} ......................................................*/
void Blinky_ctor(void) {
    Blinky *me = (Blinky *)AO_Blinky;
    QActive_ctor(&me->super, Q_STATE_CAST(&Blinky_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}
/*$enddef${AOs::Blinky_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$define${AOs::Blinky} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Blinky} ...........................................................*/

/*${AOs::Blinky::SM} .......................................................*/
static QState Blinky_initial(Blinky * const me, void const * const par) {
    /*${AOs::Blinky::SM::initial} */
    Init_State
    return Q_TRAN(&Blinky_SHORT PRESS STATE);
}

/*${AOs::Blinky::SM::SHORT PRESS STATE} ....................................*/
static QState Blinky_SHORT PRESS STATE(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::Blinky::SM::SHORT PRESS STAT~::Led OFF} ...........................*/
static QState Blinky_Led OFF(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Blinky::SM::SHORT PRESS STAT~::Led OFF::TimeOut} */
        case TimeOut_SIG: {
            status_ = Q_TRAN(&Blinky_Led ON);
            break;
        }
        /*${AOs::Blinky::SM::SHORT PRESS STAT~::Led OFF::Buttun Long Press} */
        case Buttun Long Press_SIG: {
            status_ = Q_TRAN(&Blinky_LONG PRESS STATE);
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky_SHORT PRESS STATE);
            break;
        }
    }
    return status_;
}

/*${AOs::Blinky::SM::SHORT PRESS STAT~::Led ON} ............................*/
static QState Blinky_Led ON(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Blinky::SM::SHORT PRESS STAT~::Led ON::TimeOut} */
        case TimeOut_SIG: {
            status_ = Q_TRAN(&Blinky_Led OFF);
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky_SHORT PRESS STATE);
            break;
        }
    }
    return status_;
}

/*${AOs::Blinky::SM::LONG PRESS STATE} .....................................*/
static QState Blinky_LONG PRESS STATE(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::Blinky::SM::LONG PRESS STATE::Led ON} .............................*/
static QState Blinky_Led ON(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Blinky::SM::LONG PRESS STATE::Led ON::TimeOut} */
        case TimeOut_SIG: {
            status_ = Q_TRAN(&Blinky_Led OFF);
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky_LONG PRESS STATE);
            break;
        }
    }
    return status_;
}

/*${AOs::Blinky::SM::LONG PRESS STATE::Led OFF} ............................*/
static QState Blinky_Led OFF(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Blinky::SM::LONG PRESS STATE::Led OFF::TimeOut} */
        case TimeOut_SIG: {
            status_ = Q_TRAN(&Blinky_Led ON);
            break;
        }
        /*${AOs::Blinky::SM::LONG PRESS STATE::Led OFF::Buttun Short Press} */
        case Buttun Short Press_SIG: {
            status_ = Q_TRAN(&Blinky_SHORT PRESS STATE);
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky_LONG PRESS STATE);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Blinky} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
